spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
spring.datasource.username=task_user
spring.datasource.password=task_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Optional
spring.sql.init.mode=always
spring.jpa.show-sql=true
